CREATE TABLE IF NOT EXISTS Employee (
    id SERIAL PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    department VARCHAR(20) NOT NULL,
    ChiefID INTEGER NULL,
    FOREIGN KEY (chiefID) REFERENCES Employee(id)
);